[profile.default]
libs = ['lib']
out = 'out'
solc = "0.8.20"
src = 'src'
build_info = true
extra_output = ["storageLayout"]

[profile.networks.fuji]
chain_id = 43113
rpc_url = "https://api.avax-test.network/ext/bc/C/rpc"

[profile.networks.avax]
chain_id = 43114
rpc_url = "https://api.avax.network/ext/bc/C/rpc"

[rpc_endpoints]
axax = "https://api.avax.network/ext/bc/C/rpc"
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
